set allow-duplicate-recipes := true
set ignore-comments := true

_default:
    #!/usr/bin/bash
    /usr/bin/ujust --list --list-heading $'Available commands:\n' --list-prefix $' - '

import? "/usr/share/ublue-os/just/00-default.just"
import? "/usr/share/ublue-os/just/10-update.just"
import? "/usr/share/ublue-os/just/60-custom.just"
